userValidation/config/urls.py
from django.contrib import admin
from django.urls import path, include

app_name = 'originUrl'
urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('getuser/', include('getuser.urls')),
    path('', include('mainpage.urls')),
]

userValidation/getuser/urls.py
from django.urls import path
from .views import signUp


app_name = 'getuser'
urlpatterns = [
    path('', signUp, name='signup')
]

userValidation/mainpage/urls.py
from django.urls import path
from .views import *

app_name = 'mainpage'
urlpatterns = [
    path('', myMainPage, name='mainpage'),
]

userValidation/getuser/models.py
from django.db import models

# Create your models here.

TITLE_CHOICES = [
    ('MR', 'Mr.'),
    ("MRS", 'Mrs.'),
    ('MS', 'Ms.'),
]


class GettingUserData(models.Model):
    name = models.CharField(max_length=200)
    email = models.EmailField()
    username = models.CharField(max_length=50)
    gender = models.CharField(max_length=3, choices=TITLE_CHOICES)
    password = models.CharField(max_length=20)

    def __str__(self):
        return self.username

userValidation/mainpage/models.py
from django.db import models

# Create your models here.

userValidation/getuser/forms.py
from django import forms

from .models import GettingUserData

# this class use Form and you should implement all of you want
# class SignUp(forms.Form):
#     name = forms.CharField(max_length=200, help_text="name")
#     username = forms.CharField(
#         max_length=40, required=True, help_text="username")
#     email = forms.EmailField(required=True, help_text='email')
#     password = forms.PasswordInput()


class SignUpForm(forms.ModelForm):
    class Meta:
        model = GettingUserData
        fields = ['name', 'username', 'email', 'password', 'gender']
        # widgets = {
        #     'name': (attrs={'cols': 80, 'rows': 20}),
        # }

        # this is show label in aside of inputs
        labels = {
            'name': (''),
            'username': (''),
            'email': (''),
            'password': (''),
            'gender': (''),
        }

        # show help_texts
        # help_texts = {
        #     'name': ('Some useful help text.'),
        # }

        # this is show error_messages
        error_messages = {
            'name': {
                'max_length': ("This writer's name is too long.name sould be less than 200 characters"),
            },
            'username': {
                'max_length': ("This writer's name is too long.name sould be less than 50 characters"),
            },
            # 'email': {
            #     'max_length': ("This writer's name is too long.name sould be less than 200 characters"),
            # },
            'password': {
                'max_length': ("This writer's name is too long.name sould be less than 20 characters"),
            },
            'gender': {
                'max_length': ('set your gender!')
            },
        }

userValidation/getuser/views.py
from django.shortcuts import render, HttpResponse
from django.http import HttpResponseRedirect

from .models import GettingUserData

from .forms import SignUpForm

# Create your views here.


# just show a site without form
# def signUp(request):
#     '''this method is for sign up users in app'''
#     # return HttpResponse('Hello, World!')
#     return render(request, 'getuser/index.html')


def signUp(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)

        if form.is_valid():
            form.save()
            return HttpResponse("Hello user")

    else:
        form = SignUpForm()

    context = {
        'form': form,
    }
    return render(request, 'getuser/index.html', context)

userValidation/mainpage/views.py
from django.shortcuts import render

# Create your views here.
def myMainPage(request):
    return render(request, 'mainpage/index.html')

userValidation/getuser/templates/getuser/index.html
<!-- Header -->
{% extends "base.html" %} {% block title_bar %} signup user {% endblock %}

<!-- end Header -->

<!-- Body -->

{% block body_page %}
<form action="/" method="post">
    {% csrf_token %} {{form}}
    <input type="submit" value="signup">
</form>
{% endblock %}

<!-- end Body -->

userValidation/mainpage/templates/mainpage/index.html
{% extends "base.html" %} {% block title_bar %}Main Page{% endblock %}


<!--inBody-->
{% block body_page %}
<!-- openblock -->


<a class="geturl" href="{% url 'getuser:signup' %}">signup</a>
<a class="geturl" href="/admin">admin</a>

<!-- blockended -->
{% endblock %}
<!-- endBody -->

userValidation/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title_bar %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'style/main.css' %}" />
    <link rel="stylesheet" href="{% static 'style/otherpages.css' %}" />
    <link rel="stylesheet" href="{% static 'style/getuser.css' %}" />
  </head>

  <body>
    <main>
      <!--
             TODO: last child and first child get border-radius 
            and div#childbackgroundForm remove 
        -->
      <div id="backgroundForm">
        <div id="childbackgroundForm">{% block body_page %}{% endblock %}</div>
      </div>
    </main>
  </body>
</html>